<template><el-drawer v-model="visible" size="min(720px, 96%)"><template #header><div><h2>{{scenario?.name}}</h2><span class="muted">维护测试数据、脚本与录制</span></div></template><el-tabs v-model="tab"><el-tab-pane label="基本信息" name="base"><div class="drawer-actions"><el-button type="primary" @click="formRef.open(scenario)">编辑基本信息</el-button></div><el-descriptions border :column="1"><el-descriptions-item label="场景 key">{{scenario?.key}}</el-descriptions-item><el-descriptions-item label="应用 / 模块">{{store.appName(scenario?.appId)}} / {{store.moduleName(scenario?.moduleId)}}</el-descriptions-item><el-descriptions-item label="优先级">{{scenario?.priority}}</el-descriptions-item><el-descriptions-item label="说明">{{scenario?.description||'-'}}</el-descriptions-item><el-descriptions-item label="脚本入口"><el-text tag="code">{{scenario?.scriptEntry||'尚未绑定'}}</el-text></el-descriptions-item><el-descriptions-item label="负责人">{{scenario?.owner||'-'}}</el-descriptions-item></el-descriptions></el-tab-pane><el-tab-pane label="测试数据" name="data"><div class="drawer-actions"><el-button @click="generate(false)">生成样例</el-button><el-button @click="generate(true)">AI 生成</el-button></div><el-form label-position="top"><el-form-item label="上传 Excel / CSV"><el-input v-model="datasetName" placeholder="数据集名称"/><el-upload ref="uploadRef" drag :auto-upload="false" :limit="1" accept=".csv,.xlsx" :on-change="selectFile" :on-remove="clearFile"><el-icon class="el-icon--upload"><UploadFilled/></el-icon><div>拖拽文件到这里，或点击选择</div></el-upload><el-button type="primary" :loading="uploading" :disabled="!uploadFile" @click="uploadDataset">上传数据文件</el-button></el-form-item></el-form><el-table :data="datasets" border empty-text="暂无数据集"><el-table-column prop="name" label="名称"/><el-table-column prop="rowCount" label="行数" width="80"/><el-table-column prop="createdAt" label="创建时间"/></el-table></el-tab-pane><el-tab-pane label="脚本与录制" name="record"><el-alert title="推荐使用录制快速创建脚本，再由维护人员补充断言。" type="info" show-icon/><el-form label-position="top"><el-form-item label="录制环境"><el-select v-model="environment"><el-option v-for="env in store.environments" :key="env.key" :label="env.name" :value="env.key"/></el-select></el-form-item></el-form><el-button type="primary" :icon="VideoCamera" :loading="recordLoading" @click="startRecord">开始录制</el-button><div v-if="recording" class="record-command"><strong>录制状态：{{recordStatus}}</strong><el-input v-if="recording.localCommand" :model-value="recording.localCommand" readonly><template #append><el-button @click="copy">复制</el-button></template></el-input><p v-if="recording.status!=='finished'">完成浏览器操作后，点击“完成并绑定脚本”。</p><p v-else>脚本已绑定：{{recording.scriptEntry}}</p><el-button :loading="recordLoading" @click="refresh">刷新状态</el-button><el-button v-if="recording.status!=='finished'" type="primary" :loading="recordLoading" @click="finishRecord">完成并绑定脚本</el-button></div></el-tab-pane></el-tabs><ScenarioFormDialog ref="formRef" @saved="scenarioSaved"/></el-drawer></template>
<script setup>
import{computed,ref}from'vue';import{VideoCamera,UploadFilled}from'@element-plus/icons-vue';import{ElMessage}from'element-plus';import{api}from'../api';import{usePlatformStore}from'../stores/platform';import ScenarioFormDialog from'./ScenarioFormDialog.vue';
const emit=defineEmits(['changed']),store=usePlatformStore(),visible=ref(false),scenario=ref(),tab=ref('base'),datasets=ref([]),recording=ref(),environment=ref('test'),datasetName=ref(''),uploadFile=ref(null),uploadRef=ref(),uploading=ref(false),recordLoading=ref(false),formRef=ref();
const recordStatus=computed(()=>recording.value?.status==='finished'?'已完成并绑定':'录制中');
async function loadDatasets(){datasets.value=await api(`/api/scenarios/${scenario.value.key}/datasets`)}
async function open(item){scenario.value=item;tab.value='base';recording.value=null;uploadFile.value=null;datasetName.value=`${item.name}数据`;try{await loadDatasets();environment.value=store.environments.find(e=>e.isDefault)?.key||'test';visible.value=true}catch(e){ElMessage.error(e.message)}}
async function generate(useLlm){try{const result=await api(`/api/scenarios/${scenario.value.key}/sample-data`,{method:'POST',body:JSON.stringify({count:3,useLlm})});ElMessage.success(`已生成 ${result.rows?.length||0} 行样例数据`)}catch(e){ElMessage.error(e.message)}}
function selectFile(file){uploadFile.value=file.raw;datasetName.value ||= file.name}function clearFile(){uploadFile.value=null}
async function uploadDataset(){const body=new FormData();body.append('name',datasetName.value.trim()||uploadFile.value.name);body.append('file',uploadFile.value);uploading.value=true;try{await api(`/api/scenarios/${scenario.value.key}/datasets`,{method:'POST',body});await loadDatasets();uploadRef.value.clearFiles();uploadFile.value=null;ElMessage.success('测试数据上传成功')}catch(e){ElMessage.error(e.message)}finally{uploading.value=false}}
async function startRecord(){recordLoading.value=true;try{recording.value=await api('/api/recordings/start',{method:'POST',body:JSON.stringify({scenarioKey:scenario.value.key,environmentKey:environment.value})})}catch(e){ElMessage.error(e.message)}finally{recordLoading.value=false}}
async function copy(){await navigator.clipboard.writeText(recording.value.localCommand);ElMessage.success('命令已复制')}
async function refresh(){recordLoading.value=true;try{const result=await api(`/api/recordings/${recording.value.id}`);recording.value={...recording.value,...result};if(result.status==='finished')await syncScenario(result);ElMessage.success('录制状态已刷新')}catch(e){ElMessage.error(e.message)}finally{recordLoading.value=false}}
async function finishRecord(){recordLoading.value=true;try{const result=await api(`/api/recordings/${recording.value.id}/finish`,{method:'POST',body:JSON.stringify({scenarioKey:scenario.value.key})});recording.value={...recording.value,...result};await syncScenario(result);ElMessage.success('录制已完成，脚本已绑定')}catch(e){ElMessage.error(e.message)}finally{recordLoading.value=false}}
async function syncScenario(result){if(result.scenario)scenario.value={...scenario.value,...result.scenario};else if(result.scriptEntry)scenario.value={...scenario.value,scriptEntry:result.scriptEntry};emit('changed')}
function scenarioSaved(result){scenario.value={...scenario.value,...result};emit('changed')}
defineExpose({open});
</script>
