<template><div class="page"><div class="metric-grid"><el-card><span>今日执行</span><strong>{{todayRuns}}</strong></el-card><el-card><span>近期成功率</span><strong>{{passRate}}%</strong></el-card><el-card><span>待处理失败</span><strong>{{failed}}</strong></el-card><el-card><span>可执行场景</span><strong>{{store.readyScenarios.length}}/{{store.scenarios.length}}</strong></el-card></div><div class="scenario-layout"><el-card class="tree-card"><template #header><strong>场景分类</strong></template><el-tree :data="tree" node-key="id" default-expand-all highlight-current @node-click="selectNode"/></el-card><el-card class="content-card"><template #header><div class="card-header"><div><h2>测试场景</h2><span class="muted">集中管理脚本、数据、执行和结果</span></div><el-button type="primary" :icon="Plus" @click="formRef.open()">新建场景</el-button></div></template><div class="table-toolbar"><el-input v-model="keyword" :prefix-icon="Search" placeholder="搜索场景、模块或说明" clearable/><el-segmented v-model="statusFilter" :options="['全部','可执行','需准备','草稿']"/></div><el-table :data="filtered" height="calc(100vh - 315px)" empty-text="暂无测试场景" @row-dblclick="edit"><el-table-column label="场景" min-width="300"><template #default="{row}"><div class="scenario-name"><strong>{{row.name}}</strong><span>{{row.description}}</span></div></template></el-table-column><el-table-column label="应用 / 模块" min-width="190"><template #default="{row}">{{store.appName(row.appId)}}<br><span class="muted">{{store.moduleName(row.moduleId)}}</span></template></el-table-column><el-table-column prop="priority" label="优先级" width="85"/><el-table-column label="状态" width="150"><template #default="{row}"><el-tag :type="readinessType(row)">{{readinessLabel(row)}}</el-tag></template></el-table-column><el-table-column label="近期成功率" width="120"><template #default="{row}"><el-progress :percentage="row.quality?.passRate||0" :stroke-width="7"/></template></el-table-column><el-table-column label="操作" width="230" fixed="right"><template #default="{row}"><el-button type="primary" link @click="runRef.open(row)">执行</el-button><el-button link @click="edit(row)">编辑</el-button><el-button link @click="$emit('history',row)">历史</el-button></template></el-table-column></el-table></el-card></div><RunDialog ref="runRef" @started="handleStarted"/><RunDetailDrawer ref="runDetailRef"/><ScenarioDrawer ref="editRef" @changed="store.loadCatalog()"/><ScenarioFormDialog ref="formRef" @saved="store.loadCatalog()"/></div></template>
<script setup>
import{computed,ref}from'vue';import{Plus,Search}from'@element-plus/icons-vue';import{usePlatformStore}from'../stores/platform';import RunDialog from'../components/RunDialog.vue';import RunDetailDrawer from'../components/RunDetailDrawer.vue';import ScenarioDrawer from'../components/ScenarioDrawer.vue';import ScenarioFormDialog from'../components/ScenarioFormDialog.vue';
defineEmits(['history']);const store=usePlatformStore(),runRef=ref(),runDetailRef=ref(),editRef=ref(),formRef=ref(),keyword=ref(''),statusFilter=ref('全部'),selected=ref({});
const todayRuns=computed(()=>store.runs.filter(r=>(r.startedAt||'').startsWith(new Date().toISOString().slice(0,10))).length),completed=computed(()=>store.runs.filter(r=>['passed','failed'].includes(r.status))),passRate=computed(()=>completed.value.length?Math.round(completed.value.filter(r=>r.status==='passed').length/completed.value.length*100):0),failed=computed(()=>store.runs.filter(r=>r.status==='failed').length);
const tree=computed(()=>[{id:'all',label:`全部场景（${store.scenarios.length}）`,children:store.apps.map(app=>({id:app.id,label:app.name,children:store.modules.filter(m=>m.appId===app.id).map(m=>({id:m.id,label:m.name}))}))}]);
const filtered=computed(()=>store.scenarios.filter(s=>(!keyword.value||`${s.name}${s.description}`.includes(keyword.value))&&(!selected.value.id||selected.value.id==='all'||s.appId===selected.value.id||s.moduleId===selected.value.id)&&(statusFilter.value==='全部'||readinessLabel(s)===statusFilter.value)));
function selectNode(node){selected.value=node}function readinessLabel(row){return row.status==='draft'?'草稿':row.readiness?.ready?'可执行':'需准备'}function readinessType(row){return row.status==='draft'?'warning':row.readiness?.ready?'success':'info'}function edit(row){editRef.value.open(row)}async function handleStarted(run){let detailRun=run;try{await store.loadRuns();detailRun=store.runs.find(item=>item.runId===run.runId)||run}catch{detailRun=run}runDetailRef.value.open(detailRun)}
</script>
